baseurl = ""
metaDataFormat = "toml"
title = ""
theme = "musetheme"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = false

[params]

  introTitle = ""
  introSubtitle = ""
  introBgColor = "bg-pink-300"
  introPhoto = ""
  logo = ""

  orgDbaName = ""
  orgLegalName = ""
  orgMotto = ""
  orgAddress = ""
  orgPhone = ""

  # Enable the darkmode toggle in header
  darkModeToggle = false

  # Enable search in header
  enableSearch = true

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]

  # Custom copyright - optional
  # copyright = "Copyright © 2023 Lima Buttgereit Holdings LLC d/b/a Muse Systems"
  favicon = ""


  # The page bundle that contains service details.  Leave unset to omit section.
  serviceBundle = "services"
  showServiceMeta = false
  showServiceToc = false

  # The page bundle that contains the site's blog.  Leave unset to omit section.
  blogBundle = "blog"
  showBlogMeta = true
  showBlogToc = true

  showMidSection = false
  midSectionBgColor = "bg-pink-300"
  footerBgColor = "bg-pink-300"

  # Default metadata visibility if page Type is unknown. Omission defaults to true.
  showMeta = true

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  defaultBgColor = "bg-pink-300"


  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = true

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  showToc = true

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = false

# Comments system
[params.comments]
  # Supports disqus, giscus and utterances
  # Check hugo docs for setting up disqus
  system = ""

  # Options for giscus, exclude hyphens
  repo = ""
  repoid = ""
  category = ""
  categoryid = ""
  mapping = ""
  strict = ""
  reactionsenabled = ""
  emitmetadata = ""
  inputposition = ""
  theme = ""

  # Options for utterances, exclude hyphens
  # repo = ""
  # issueterm = ""
  # theme = ""


# [[params.homepage.social.icons]]
#   website = "github"
#   url = "https://github.com/MuseSystems"

# [[params.footer.links]]
#   title = "Acknowledgements"
#   url = "/acknowledgements"
  weight = 10


# [[menu.main]]
#   name = "About"
#   url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true

[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = [':git', 'lastmod', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']
