baseurl = "https://muse.systems"
metaDataFormat = "toml"
title = "Muse Systems"
theme = "musetheme"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = false

googleAnalytics = 'G-WVGYZZD2K1'

[params]

  introTitle = "Inspired Solutions for Business"
  introSubtitle = "Muse Systems is a San Francisco based business systems consultancy experienced in implementation management, design, and development.  Serving clients in the distribution, manufacturing, and retail industries."
  introBgColor = "bg-gray-300"
  introPhoto = "/img/landing/experience.webp"

  logo = "/img/brand/musesystems-logo-optimized.svg"

  orgDbaName = "Muse Systems"
  orgLegalName = "Lima Buttgereit Holdings LLC d/b/a Muse Systems"
  orgMotto = "Inspired Solutions for Business"
  orgAddress = """\
    18 Dorado Terrace, Unit. 8
    San Fransisco, CA 94112
    USA
    """
  orgPhone = "415.404.9502"

  # Enable the darkmode toggle in header
  darkModeToggle = false

  # Enable search in header
  enableSearch = true

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    # "content",
    "link",
    "author"
  ]

  # Custom copyright - optional
  # copyright = "Copyright © 2023 Lima Buttgereit Holdings LLC d/b/a Muse Systems"
  favicon = "/img/brand/favicon.svg"


  # The page bundle that contains service details.  Leave unset to omit section.
  serviceBundle = "services"
  showServiceMeta = false
  showServiceToc = false
  showServicePager = true


  # The page bundle that contains the site's blog.  Leave unset to omit section.
  blogBundle = "blog"
  showBlogMeta = true
  showBlogToc = true
  showBlogPager = true


  showMidSection = true
  midSectionBgColor = "bg-gray-300"
  footerBgColor = "bg-gray-300"

  # Default metadata visibility if page Type is unknown. Omission defaults to true.
  showMeta = false

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  defaultBgColor = "bg-gray-300"


  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = true

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  showToc = false

  # Add support for section Pager
  showPager = false

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = false

# Comments system
[params.comments]
  # Supports disqus, giscus and utterances
  # Check hugo docs for setting up disqus
  system = ""

  # Options for giscus, exclude hyphens
  repo = ""
  repoid = ""
  category = ""
  categoryid = ""
  mapping = ""
  strict = ""
  reactionsenabled = ""
  emitmetadata = ""
  inputposition = ""
  theme = ""

  # Options for utterances, exclude hyphens
  # repo = ""
  # issueterm = ""
  # theme = ""


[[params.homepage.social.icons]]
  website = "github"
  url = "https://github.com/MuseSystems"

[[params.homepage.social.icons]]
  website = "linkedin"
  url = "https://www.linkedin.com/company/muse-systems/"

[[params.footer.links]]
  title = "Acknowledgements"
  url = "/acknowledgements"
  weight = 10


[[menu.main]]
  name = "About"
  url = "/about"
  weight = 10

# [[menu.main]]
#   name = "Tags"
#   url = "tags"
#   weight = 10

[[menu.main]]
  name = "Contact Us"
  url = "/contact"
  weight = 30

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    hardWraps = true
    unsafe = true

[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = [':git', 'lastmod', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']
