name = "musetheme"
license = "Apache v2.0"
licenselink = "https://github.com/MuseSystems/muse.systems/blob/master/LICENSE"
description = "Hugo site source for Muse System related marketing sites."
homepage = "https://muse.systems"
demosite = "https://muse.systems"
tags = ["Hugo", "theme", "blog", "modern", "responsive"]
features = ["clean", "gallery", "minimal", "minimalist", "mobile", "personal", "responsive", "simple", "tailwind", "blog", "white"]
min_version = "0.82.1"

[author]
  name = "Steven C. Buttgereit"
  homepage = "https://muse.systems"
